/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "RPC_xFile.h"

bool_t
xdr_Inserimento (XDR *xdrs, Inserimento *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->descrizione, 25,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->tipo, 10,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->gg))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mm))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aaaa))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->gg);
		IXDR_PUT_LONG(buf, objp->mm);
		IXDR_PUT_LONG(buf, objp->aaaa);
		}
		 if (!xdr_vector (xdrs, (char *)objp->luogo, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->disponibilita))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->prezzo))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->descrizione, 25,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->tipo, 10,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->gg))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->mm))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->aaaa))
				 return FALSE;

		} else {
		objp->gg = IXDR_GET_LONG(buf);
		objp->mm = IXDR_GET_LONG(buf);
		objp->aaaa = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->luogo, 20,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->disponibilita))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->prezzo))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->descrizione, 25,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->tipo, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->gg))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->mm))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->aaaa))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->luogo, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->disponibilita))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prezzo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Acquisto (XDR *xdrs, Acquisto *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->descrizione, 25,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nBiglietti))
		 return FALSE;
	return TRUE;
}
